# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_note_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
from PySide2.QtWidgets import QApplication, QDialog, QLineEdit, QDateEdit, QTimeEdit, QHBoxLayout, QCheckBox, \
	QVBoxLayout
from PySide2.QtGui import QFont
from PySide2 import QtCore


class NoteForm2(QDialog):
	def __init__(self):
		super().__init__(None)  # , QtCore.Qt.WindowSystemMenuHint | QtCore.Qt.WindowTitleHint

		self.resize(400, 300)
		self.verticalLayout = QVBoxLayout(self)
		self.verticalLayout.setContentsMargins(30, 30, 30, 30)
		self.verticalLayout.setSpacing(0)
		self.verticalLayout.setObjectName("verticalLayout")

		self.title = QLineEdit(self)
		self.title.setObjectName("title")
		self.verticalLayout.addWidget(self.title)

		self.description = QLineEdit(self)
		self.description.setObjectName("description")
		self.verticalLayout.addWidget(self.description)

		self.date_picker = QDateEdit(calendarPopup=True)
		self.date_picker.setObjectName("date_picker")
		self.verticalLayout.addWidget(self.date_picker)

		self.horizontalLayout_2 = QHBoxLayout()
		self.horizontalLayout_2.setObjectName("horizontalLayout_2")
		self.verticalLayout.addLayout(self.horizontalLayout_2)

		self.enable_time = QCheckBox(self)
		self.enable_time.setObjectName("enable_time")
		self.horizontalLayout_2.addWidget(self.enable_time)

		self.time_picker = QTimeEdit(self)
		self.time_picker.setEnabled(False)
		self.time_picker.setObjectName("time_picker")
		self.horizontalLayout_2.addWidget(self.time_picker)

		self.retranslate_ui()
		QtCore.QMetaObject.connectSlotsByName(self)

	def retranslate_ui(self):
		_translate = QtCore.QCoreApplication.translate
		self.title.setPlaceholderText(_translate("self", "Add title"))
		self.description.setPlaceholderText(_translate("self", "Add description"))
		self.setWindowTitle(_translate("self", "self"))
		self.enable_time.setText(_translate("self", "Add a time"))


if __name__ == '__main__':
	segoe_font = QFont("Segoe UI Light", 10)

	app = QApplication(sys.argv)
	app.setFont(segoe_font)

	window = NoteForm2()
	window.show()
	sys.exit(app.exec_())
